language: python
python:
  - 3.6
install:
  # update package repositories
  - sudo apt-get update
  # setup conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # check conda info
  - conda info -a
  # setup the environment
  - conda env create -f conda.yml
  - conda activate data-preprocessor
  # install data-preprocessor
  - pip install .
  # install dev dependencies
  - pip install -r test_requirements.txt
script:
  - |
    yapf --quiet --style "{based_on_style: pep8, blank_line_before_nested_class_or_def: true, indent_dictionary_value: true, dedent_closing_brackets: true, column_limit: 99}" --recursive bio_rxn
  - python3 -m pytest -sv --cov=bio_rxn --cov-fail-under=50
  - python3 -m flake8 --disable-noqa bio_rxn
  - mypy bio_rxn
